set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_DISABLE_COMPILER_TRACKING ON)
set(VCPKG_CXX_FLAGS "/D_WIN32_WINNT=0x0A00 /DWINVER=0x0A00")
set(VCPKG_C_FLAGS "/D_WIN32_WINNT=0x0A00 /DWINVER=0x0A00")
